spring:
  datasource:
    url: jdbc:mysql://106.54.88.89:3306/test1?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: MIN@lan3102
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    template-loader-path: classpath:/templates/
  mybatis:
    configuration:
      map-underscore-to-camel-case: true
  resources:
    static-locations: classpath:/resources/static/




